MainServerIsMirror: false
BananaMirrorConfig: # omit to disable mirroring
  KnownHosts: path/to/file
  ServerAddress: serveraddress
  Username: username
  Password: password
  Directory: directory/on/sftp/server
  ImagesDirectory: other/directory/on/sftp/server